init:
  detector: COCOA

  gpu: 0
  chunk_size: 256
  batch_size: 256
  num_workers: 2
  precision: medium

  model:
    config_path_v   : /saved_checkpoints/cocoaxminixv1x250kxs1xxxer4oji6g/config_v.yml
    config_path_ms1 : /saved_checkpoints/cocoaxminixv1x250kxs1xxxer4oji6g/config_ms1.yml
    config_path_t   : /saved_checkpoints/cocoaxminixv1x250kxs1xxxer4oji6g/config_t.yml
    checkpoint_path : /saved_checkpoints/cocoaxminixv1x250kxs1xxxer4oji6g/checkpoints/epoch=79-val_total_loss=0.0799.ckpt

  ind_threshold_loose: 0.2


items:
  - info: "dijet train"
    seg_path: |
      glob.glob('path to train/cocoa_dijet_chunk_*_seg_bw0.4.root')
    dir_flag: 'dijet'
    output_path: null
    n_events: -1


  - info: "dijet val"
    seg_path: |
      glob.glob('path to val/cocoa_dijet_chunk_*_seg_bw0.4.root')
    dir_flag: 'dijet'
    output_path: null
    n_events: -1
